// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VicStelmak.DEFDA.Infrastructure.DataAccess;

#nullable disable

namespace VicStelmak.DEFDA.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    partial class LeaseholdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VicStelmak.DEFDA.BusinessLogic.Models.AddressModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("City")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int?>("LeaseholderId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("Region")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("LeaseholderId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("VicStelmak.DEFDA.BusinessLogic.Models.EmailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int?>("LeaseholderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaseholderId");

                    b.ToTable("EmailAddresses", (string)null);
                });

            modelBuilder.Entity("VicStelmak.DEFDA.BusinessLogic.Models.LeaseholderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Leaseholders", (string)null);
                });

            modelBuilder.Entity("VicStelmak.DEFDA.BusinessLogic.Models.AddressModel", b =>
                {
                    b.HasOne("VicStelmak.DEFDA.BusinessLogic.Models.LeaseholderModel", "LeaseholderModel")
                        .WithMany("Addresses")
                        .HasForeignKey("LeaseholderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LeaseholderModel");
                });

            modelBuilder.Entity("VicStelmak.DEFDA.BusinessLogic.Models.EmailModel", b =>
                {
                    b.HasOne("VicStelmak.DEFDA.BusinessLogic.Models.LeaseholderModel", "LeaseholderModel")
                        .WithMany("EmailAddresses")
                        .HasForeignKey("LeaseholderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LeaseholderModel");
                });

            modelBuilder.Entity("VicStelmak.DEFDA.BusinessLogic.Models.LeaseholderModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("EmailAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
